- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: Shivakumar"
  
  - name: print the infomation again
    vars: #task level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: Shivakumar"

  - name: print the infomation again
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: Shivakumar"