- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: printing information again
    ansible.builtin.debug:
      msg: "im learning {{COURSE}} and duration is {{DURATION}}"