- name: install server and run
  hosts: web
  become: true
  tasks:
  - name: install server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.server:
      name: nginx
      enabled: yes
      state: started

