- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars:
   number: 200 # number
  tasks:
  - name: Print number if less than 20
    ansible.builtin.debug:
      msg: "Given {{ number }} is less than 20"
    when: number < 20
  
  - name: Print number if greate than or equal 20
    ansible.builtin.debug:
      msg: "Given {{ number }} is greater than or equal to 20"
    when: number >= 20