- name: create heterogenious OS and install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: " {{ ansible_facts }}"

  - name: install nginx if Redhat
    ansible.builtin.dnf:
      name: nginx
      state: yes
    when: ansible_os_family == "RedHat"

  - name: install nginx if its debian
    ansible.builtin.apt:
      name: nginx
      state: yes
    when: ansible_os_family == "Debian"

    
