- name: functions and filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: " Hello {{ course | default('ansible') }}"

  - name: print the upper case
    vars:
      wishes: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " wishes | upper "