- name: functions and filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: " Hello {{ course | default('ansible') }}"

  - name: print the upper case
    vars:
      wishes: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ wishes | upper }}"

  - name: print the lower case
    vars:
      greetings: HELLO TEJASWINI
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

  - name: print uniqe numbers
    vars: 
      numbers: [1,2,3,3,4,45,590,5,6]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: print min and max numbers
    vars:
      numbers: [1,2,3,3,4,45,590,5,6]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: 120 hours
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
        name: "Devops with AWS"
        duration: 120 hours
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

        