- name: command Vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the command
      ansible.builtin.shell: ls -ltr > /tmp/output.txt # login to the server and execute command
      # command module, just issues the command

    - name: check the process
      ansible.builtin.shell: ps -ef | grep ssh # it will execute the command and register the output
      register: output
        
