- name: create ec2 instances and route53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-08ea5da683da5d4d8
    sg_id: sg-0e7c43787ee29017f
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loops: "{{ instances }}"
    register: ec2_instance
    
