- name: create ec2 instances and route53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-08ea5da683da5d4d8
    sg_id: sg-0e7c43787ee29017f
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: tejudevops.shop
  tasks:
  - name: create instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t2.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
    
  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.tejudevops.shop
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true # whenever there are existing records
    loop: "{{ ec2_instances.results }}"